// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4J9QuFQixfF1MbPrpkWGUcSvgyHtGfxE',
    appId: '1:680152053567:web:5878e63c2daad672ccc58a',
    messagingSenderId: '680152053567',
    projectId: 'select-languages',
    authDomain: 'select-languages.firebaseapp.com',
    storageBucket: 'select-languages.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxbthWkfhpbvs6Jb8KGFmUZhotxcz4kRc',
    appId: '1:680152053567:android:5db3ed90560074b4ccc58a',
    messagingSenderId: '680152053567',
    projectId: 'select-languages',
    storageBucket: 'select-languages.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuE3Y5CCqp2pyFbL78hcCGdg722gze8HQ',
    appId: '1:680152053567:ios:44b3a4cab487d099ccc58a',
    messagingSenderId: '680152053567',
    projectId: 'select-languages',
    storageBucket: 'select-languages.firebasestorage.app',
    androidClientId: '680152053567-emkdlcus6e32uip0iai5n9mju9um4lqb.apps.googleusercontent.com',
    iosClientId: '680152053567-ohe8r3a5dba9i28fd1lre7tidbe4bufl.apps.googleusercontent.com',
    iosBundleId: 'com.longndutc.publicchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuE3Y5CCqp2pyFbL78hcCGdg722gze8HQ',
    appId: '1:680152053567:ios:44b3a4cab487d099ccc58a',
    messagingSenderId: '680152053567',
    projectId: 'select-languages',
    storageBucket: 'select-languages.firebasestorage.app',
    androidClientId: '680152053567-emkdlcus6e32uip0iai5n9mju9um4lqb.apps.googleusercontent.com',
    iosClientId: '680152053567-ohe8r3a5dba9i28fd1lre7tidbe4bufl.apps.googleusercontent.com',
    iosBundleId: 'com.longndutc.publicchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4J9QuFQixfF1MbPrpkWGUcSvgyHtGfxE',
    appId: '1:680152053567:web:3b9a18c8faedc05cccc58a',
    messagingSenderId: '680152053567',
    projectId: 'select-languages',
    authDomain: 'select-languages.firebaseapp.com',
    storageBucket: 'select-languages.firebasestorage.app',
  );

}